#run 'docker compose up -d' to start services
services:
  backend:
    container_name: backend
    image: kieranparanjpe/url-shortener:1.0.0
    environment:
      - RUN_MODE=dockerProduction
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_postgresql
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}